### ISSUE TITLE
Bump leanVM pin to devnet5 commit 3f2116d (better perf, no global_allocator)

### ISSUE THREAD

**Issue by mananuf** [developerlongs/gean#347]
## Summary

Bump the leanVM dependency pin to the latest devnet5 commit `3f2116d`.

Per Emile (TG): the latest devnet5 commit of leanVM brings **better performance** and **removes the `global_allocator`** — all the memory-allocation work is now handled internally, making it easier to integrate with. This is **not a snark breaking-change** (i.e. not a mandatory upgrade), so we can schedule it rather than rush it.

## Current pin

`xmss/rust/multisig-glue/Cargo.toml` pins the three leanVM crates at:

```
rec_aggregation = { git = "https://github.com/leanEthereum/leanVM.git", rev = "8fcbd77958a58666e828315de2d6ce7c93297117" }
leansig_wrapper = { git = "https://github.com/leanEthereum/leanVM.git", rev = "8fcbd77958a58666e828315de2d6ce7c93297117" }
backend         = { git = "https://github.com/leanEthereum/leanVM.git", rev = "8fcbd77958a58666e828315de2d6ce7c93297117" }
```

Target: bump all three to `3f2116d`.

## Known blocker (from a prior attempt)

Bumping to `3f2116d` transitively bumps **Plonky3** (`5739e64a` → `21b3fa64`). The newer `p3-util` uses the unstable `maybe_uninit_slice` feature, which fails to compile on our pinned **Rust 1.90** toolchain:

```
error[E0658]: use of unstable library feature `maybe_uninit_slice`
```

So this bump requires a **Rust toolchain upgrade** first (infra change). Since Emile confirmed it's non-mandatory, the toolchain bump and this leanVM bump should be sequenced as their own PRs.

## Acceptance criteria

- [x] Rust toolchain upgraded to a version that supports the new Plonky3 (`maybe_uninit_slice` stabilized or otherwise resolved); `make ffi` / CI Rust pin updated together
- [x] All three leanVM crates pinned to `3f2116d` in `xmss/rust/multisig-glue/Cargo.toml`, lockfile updated (`cargo update -p rec_aggregation -p leansig_wrapper -p backend`)
- [x] `make ffi`, `make test-ffi`, `make lint` green
- [x] No `global_allocator` integration assumptions remain on our side (verify FFI memory handling still correct)
- [ ] Spec fixtures / signature tests still pass (snark output unchanged — non-breaking)
